version: "3"
services:

  grin-node:
    image: vanities/grin:latest
    working_dir: /grin/target/release/
    network_mode: "host"
    command: ./grin --floonet

  grin-wallet:
    image: vanities/grin:latest
    network_mode: "host"
    working_dir: /grin/target/release/
    command: bash -c "echo 'password' | ./grin --floonet wallet listen"

  grin-miner:
    image: vanities/grin:latest
    network_mode: "host"
    working_dir: /grin-miner/target/debug/
    command: ./grin-miner --floonet

    
    #ports:
    #  - "3413:3413" # api
    #  - "3414:3414"
    #  - "3415:3415" # wallet
    #  - "3416:3416" # stratum
