#########################################
### LOGGING CONFIGURATION             ###
#########################################

[logging]

# Whether to log to stdout
log_to_stdout = true

# Log level for stdout: Critical, Error, Warning, Info, Debug, Trace
stdout_log_level = "Info"

# Whether to log to a file
log_to_file = true

# Log level for file: Critical, Error, Warning, Info, Debug, Trace
file_log_level = "Debug"

# Log file path
log_file_path = "grin-miner.log"

# Whether to append to the log file (true), or replace it on every run (false)
log_file_append = true

#########################################
### MINING CLIENT CONFIGURATION       ###
#########################################

[mining]

# whether to run the tui
run_tui = false

# listening grin stratum server url
stratum_server_addr = "us-east-stratum.grinmint.com:4416"

# login for the stratum server (if required)
stratum_server_login = "mischkeaa+someuser@gmail.com/vanities"

# password for the stratum server (if required)
stratum_server_password = "some-password"

# whether tls is enabled for the stratum server
stratum_server_tls_enabled = true

### DEFAULTS
# listening grin stratum server url
#stratum_server_addr = "127.0.0.1:13416"

# login for the stratum server (if required)
#stratum_server_login = "http://192.168.1.100:13415"

# password for the stratum server (if required)
#stratum_server_password = "x"

# whether tls is enabled for the stratum server
#stratum_server_tls_enabled = false


# mean OpenCL supports both NVidia and AMD
# to install run ./install_ocl_plugins.sh script
[[mining.miner_plugin_config]]
plugin_name = "ocl_cuckaroo"
[mining.miner_plugin_config.parameters]
platform = 0
device = 0

[[mining.miner_plugin_config]]
plugin_name = "ocl_cuckaroo"
[mining.miner_plugin_config.parameters]
platform = 0
device = 1

[[mining.miner_plugin_config]]
plugin_name = "ocl_cuckaroo"
[mining.miner_plugin_config.parameters]
platform = 0
device = 2

[[mining.miner_plugin_config]]
plugin_name = "ocl_cuckaroo"
[mining.miner_plugin_config.parameters]
platform = 0
device = 3

[[mining.miner_plugin_config]]
plugin_name = "ocl_cuckaroo"
[mining.miner_plugin_config.parameters]
platform = 0
device = 4

[[mining.miner_plugin_config]]
plugin_name = "ocl_cuckaroo"
[mining.miner_plugin_config.parameters]
platform = 0
device = 5

# The fastest cpu algorithm, but consumes the most memory

#[[mining.miner_plugin_config]]
#plugin_name = "cuckaroo_cpu_compat_29"
#[mining.miner_plugin_config.parameters]
#nthreads = 1
